### ISSUE TITLE
Library not compatible with the newest Google Billing Library

### ISSUE THREAD

**Issue by michalgwo** [BranchMetrics/android-branch-deep-linking#1289]
### Describe the bug

In the [recent release of Google Play Billing Library](https://developer.android.com/google/play/billing/release-notes#8-0-0), they removed `enablePendingPurchases()` method. `enablePendingPurchases(PendingPurchaseParams params)` should be used instead.

Because of that, when I updated the Google Billing Library to 8.0.0, the app crashes on
``` kotlin
Branch.getInstance().logEventWithPurchase(this, purchase)
```
```
Process: com.app, PID: 30442
java.lang.NoSuchMethodError: No virtual method enablePendingPurchases()Lcom/android/billingclient/api/BillingClient$Builder; in class Lcom/android/billingclient/api/BillingClient$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingClient$Builder' appears in /data/app/~~_ukJYLwtEshuXh4rVA9zJw==/com.app-8Sxlyxgdsj0BNFEEBGDPeg==/base.apk!classes26.dex)
	at io.branch.referral.BillingGooglePlay$Companion.getInstance(BillingGooglePlay.kt:25)
	at io.branch.referral.Branch.logEventWithPurchase(Branch.java:2658)
	at com.app.processPurchaseList(AndroidBillingDataSource.kt:197)
	at com.app.handleRefreshPurchasesResult(AndroidBillingDataSource.kt:161)
	at com.app.refreshPurchases(AndroidBillingDataSource.kt:155)
	at com.app$refreshPurchases$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5b187dc, Dispatchers.Default]

```

### Steps to reproduce

1. Use Google Billing Library 8.0.0
2. run `Branch.getInstance().logEventWithPurchase(this, purchase)`

### Expected behavior

Not crashing

### SDK Version

5.19.0

### Make and Model

Xiaomi Redmi Note 13

### OS

Android 14

**Comment by gdeluna-branch** [comment]
Thanks for raising this, we'll take a look.

**Comment by JDM8** [comment]
Exact same issue, reverting to Play Billing 7 for now.

**Comment by JDM8** [comment]
Any progress on this issue? Unable to update Play Billing and keep Branch, and at some point we'll need to update Play Billing.

**Comment by bigman212** [comment]
Its been already a year after this was found, any news?
We really would love to bump billing version up but the Branch's billing version is a blocker rn.

**Comment by JDM8** [comment]
> Thanks for raising this, we'll take a look.

Sorry to bug you again @gdeluna-branch, but the issue is becoming more concerning as it is likely we'll have to stop using Branch in August if this is not addressed:

Deprecation Schedule: Google typically requires all new apps and updates to support the latest version by August of the year following its release. For example:
PBL 7 must be used by August 31, 2025.
**PBL 8 must be used by August 31, 2026.**
PBL 9 will likely become mandatory for new updates around August 2027.

**Comment by MUSE-CODE-SPACE** [comment]
Same situation here, so adding some detail that may help others until Branch ships a fix.

The crash happens because Play Billing 8.0.0 removed the deprecated no-arg `BillingClient.Builder.enablePendingPurchases()`. Branch's `BillingGooglePlay` was compiled against the old API, so as soon as your app bundles billing-ktx 8.x, the call site resolves to a method that no longer exists → `NoSuchMethodError` at runtime. The actual fix has to land in the Branch SDK — it needs to build its internal client with the params-based API introduced in Billing 7:

```kotlin
BillingClient.newBuilder(context)
    .setListener(listener)
    .enablePendingPurchases(
        PendingPurchasesParams.newBuilder()
            .enableOneTimeProducts()
            .build()
    )
    .build()
```

Interim workaround that lets you upgrade to Billing 8 today: stop calling `Branch.getInstance().logEventWithPurchase(...)` (that's the path that lazily constructs Branch's internal `BillingClient`), and log the purchase event manually from the `Purchase`/`ProductDetails` you already have:

```kotlin
BranchEvent(BRANCH_STANDARD_EVENT.PURCHASE)
    .setCurrency(CurrencyType.getValue(currencyCode))
    .setRevenue(priceMicros / 1_000_000.0)
    .addContentItems(
        BranchUniversalObject()
            .setCanonicalIdentifier(productId)
            .setContentMetadata(
                ContentMetadata()
                    .setPrice(priceMicros / 1_000_000.0, CurrencyType.getValue(currencyCode))
                    .setProductName(title)
                    .setQuantity(1.0)
            )
    )
    .logEvent(context)
```

This keeps attribution data flowing without Branch ever touching the Billing library. We went through the same `enablePendingPurchases(PendingPurchasesParams)` migration in our own billing code, and given Google's deadline for PBL updates, it would be great to get a maintainer ETA on this.

**Comment by bboothe-branch** [comment]
Hi everyone. Thanks for bringing this to our attention again. We will prioritize this for the next sprint.

**Comment by bboothe-branch** [comment]
Hi everyone. We released a fix for this today in our latest update version 5.21.2.
